### ISSUE TITLE
PA - Review Reviews

### ISSUE THREAD

**Issue by zzachsmith** [zzachsmith/DogHousebnb#3]
- [x] Review creation

- [x] styling

**Comment by wongshington** [comment]
- [ ] move the body of the review in a little bit so the whole review is indented from the left
- [ ] remove the a tag around the contents of the review body, shouldn't be an a tag html element
- [ ] the description body should have it's own html element so you can style it later

**Comment by wongshington** [comment]
- [ ] a little bit more space between reviews
- [ ] more space between description and "Review"

**Comment by zzachsmith** [comment]
reviews is ready to be assessed again, thank you
